"""
Quick test script for LLM-enhanced Bingo Agent
"""
import asyncio
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

from src.models import (
    UserProfile,
    EngagementState,
    BehavioralArchetype,
    TripHistory,
    BingoHistory,
    TransportMode,
)
from src.memory import SQLiteMemoryStore
from src.graph import LLMBingoAgentGraph


async def quick_test():
    print("🤖 Testing LLM-Enhanced Bingo Agent with GPT-4o-mini\n")

    # Check API key
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("❌ ERROR: OPENAI_API_KEY not found!")
        print("   Please set your API key in .env file")
        return

    print(f"✅ API Key configured: {api_key[:20]}...\n")

    # Initialize
    memory = SQLiteMemoryStore(db_path="./test_llm.db")
    await memory.initialize()
    agent = LLMBingoAgentGraph(memory)

    # Show LLM info
    info = agent.get_llm_info()
    print(f"Model: {info['model']}")
    print(f"Temperature: {info['temperature']}\n")

    # Create test user
    print("Creating test user...")
    user = UserProfile(
        user_id="test_user",
        current_engagement_state=EngagementState.STATE_4_ACTIVE,
        behavioral_archetype=BehavioralArchetype.DRIVER_HEAVY,
        trip_history=TripHistory(
            primary_modes=[TransportMode.DRIVING],
            trip_frequency=20,
        ),
        bingo_history=BingoHistory(),
    )
    await memory.save_user_profile(user)
    print("✅ User created\n")

    # Generate card
    print("🎲 Generating personalized Bingo card...")
    result = await agent.generate_card_for_user("test_user")

    if result.card_generation_response.success:
        card = result.card_generation_response.card
        print(f"\n✅ Card Generated!")
        print(f"Profile: {card.tile_profile.value}")
        print(f"Dimension: {card.dimension.value}\n")

        print("📋 Tiles (generated by GPT-4o-mini):")
        for i, tile in enumerate(card.tiles, 1):
            mode = f"[{tile.transport_mode.value}]" if tile.transport_mode else "[general]"
            print(f"{i:2d}. {tile.description:40s} {mode}")

        print("\n🎉 Success! LLM integration is working!")

    else:
        print(f"❌ Failed: {result.card_generation_response.reason}")


if __name__ == "__main__":
    asyncio.run(quick_test())
