"""
LLM-Enhanced Bingo Agent Demo

This example demonstrates how the agent uses GPT-4o-mini to:
1. Generate personalized and engaging Bingo tile descriptions
2. Create motivating reminder messages tailored to each user
3. Adapt content based on user's engagement state and behavior

Prerequisites:
- OPENAI_API_KEY set in .env file
- All dependencies installed (pip install -r requirements.txt)
"""
import asyncio
import logging
import os
from datetime import datetime
from dotenv import load_dotenv

from src.models import (
    UserProfile,
    EngagementState,
    BehavioralArchetype,
    TripHistory,
    BingoHistory,
    TransportMode,
    FeedbackEvent,
)
from src.memory import SQLiteMemoryStore
from src.graph import LLMBingoAgentGraph

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()


def print_section(title: str):
    """Print a formatted section header"""
    print("\n" + "="*70)
    print(f"  {title}")
    print("="*70 + "\n")


async def demo_llm_card_generation():
    """Demo 1: LLM-Generated Personalized Bingo Cards"""
    print_section("DEMO 1: LLM-Generated Personalized Bingo Cards")

    # Initialize
    memory_store = SQLiteMemoryStore(db_path="./llm_demo.db")
    await memory_store.initialize()
    agent = LLMBingoAgentGraph(memory_store)

    # Display LLM info
    llm_info = agent.get_llm_info()
    print("🤖 LLM Configuration:")
    print(f"   Model: {llm_info['model']}")
    print(f"   Temperature: {llm_info['temperature']}")
    print(f"   Features: {', '.join(llm_info['features'])}")
    print()

    # Create user profiles with different characteristics
    users = [
        {
            "user_id": "driver_dave",
            "name": "Driver Dave",
            "state": EngagementState.STATE_3_PRE_ACTIVE,
            "archetype": BehavioralArchetype.DRIVER_HEAVY,
            "primary_modes": [TransportMode.DRIVING],
            "description": "New user, primarily drives"
        },
        {
            "user_id": "transit_tina",
            "name": "Transit Tina",
            "state": EngagementState.STATE_4_ACTIVE,
            "archetype": BehavioralArchetype.OCCASIONAL_TRANSIT,
            "primary_modes": [TransportMode.TRANSIT, TransportMode.WALKING],
            "description": "Active user, uses transit and walks"
        },
        {
            "user_id": "multimodal_mike",
            "name": "Multimodal Mike",
            "state": EngagementState.STATE_5_ENGAGED,
            "archetype": BehavioralArchetype.MULTIMODAL_ACTIVE,
            "primary_modes": [TransportMode.BIKING, TransportMode.WALKING, TransportMode.TRANSIT],
            "description": "Power user, uses all modes"
        }
    ]

    for user_data in users:
        print(f"\n{'─'*70}")
        print(f"👤 User: {user_data['name']}")
        print(f"   {user_data['description']}")
        print(f"   State: {user_data['state'].value}")
        print(f"   Archetype: {user_data['archetype'].value}")
        print(f"{'─'*70}")

        # Create user profile
        user_profile = UserProfile(
            user_id=user_data["user_id"],
            current_engagement_state=user_data["state"],
            behavioral_archetype=user_data["archetype"],
            trip_history=TripHistory(
                primary_modes=user_data["primary_modes"],
                trip_frequency=20,
                common_travel_times=["AM_Commuter"],
                mode_distribution={mode: 10 for mode in user_data["primary_modes"]}
            ),
            bingo_history=BingoHistory(
                cards_offered=0 if user_data["state"] == EngagementState.STATE_3_PRE_ACTIVE else 5,
                cards_participated=0 if user_data["state"] == EngagementState.STATE_3_PRE_ACTIVE else 4,
                cards_completed=0 if user_data["state"] == EngagementState.STATE_3_PRE_ACTIVE else 3,
            )
        )
        await memory_store.save_user_profile(user_profile)

        # Generate card with LLM
        print("\n🎲 Generating personalized Bingo card with LLM...")
        result = await agent.generate_card_for_user(user_data["user_id"])

        if result.card_generation_response and result.card_generation_response.success:
            card = result.card_generation_response.card
            print(f"\n✅ Card Generated!")
            print(f"   Card ID: {card.card_id}")
            print(f"   Profile: {card.tile_profile.value}")
            print(f"   Dimension: {card.dimension.value}")
            print(f"   Duration: {card.duration_days} days")

            print(f"\n📋 Personalized Tiles (generated by GPT-4o-mini):")
            for i, tile in enumerate(card.tiles, 1):
                mode_str = f"[{tile.transport_mode.value}]" if tile.transport_mode else "[general]"
                nudge_str = "🎯 NUDGE" if tile.is_nudge else "      "
                diff_str = "⭐" * int(tile.difficulty_score)
                print(f"   {i:2d}. {tile.description:45s} {mode_str:12s} {nudge_str}  {diff_str}")

            print(f"\n💡 Notice how the LLM:")
            print(f"   - Adapts tile difficulty to user's engagement state")
            print(f"   - Uses engaging language and clear descriptions")
            print(f"   - Balances familiar modes with gentle nudges")

        else:
            print(f"❌ Card generation failed: {result.card_generation_response.reason}")

        # Small delay between users
        await asyncio.sleep(1)


async def demo_llm_reminder_messages():
    """Demo 2: LLM-Generated Personalized Reminder Messages"""
    print_section("DEMO 2: LLM-Generated Personalized Reminder Messages")

    memory_store = SQLiteMemoryStore(db_path="./llm_demo.db")
    await memory_store.initialize()
    agent = LLMBingoAgentGraph(memory_store)

    # Simulate different reminder scenarios
    scenarios = [
        {
            "user_id": "driver_dave",
            "name": "Driver Dave",
            "progress": 0,
            "scenario": "Card stalled (no progress)"
        },
        {
            "user_id": "transit_tina",
            "name": "Transit Tina",
            "progress": 75,
            "scenario": "High progress, running out of time"
        },
        {
            "user_id": "multimodal_mike",
            "name": "Multimodal Mike",
            "progress": 40,
            "scenario": "Low progress, expiring soon"
        }
    ]

    for scenario in scenarios:
        print(f"\n{'─'*70}")
        print(f"👤 User: {scenario['name']}")
        print(f"   Scenario: {scenario['scenario']}")
        print(f"   Progress: {scenario['progress']}%")
        print(f"{'─'*70}")

        # Get user's active card
        card = await memory_store.get_active_card(scenario["user_id"])

        if card:
            # Simulate partial progress
            tiles_to_complete = int(len(card.tiles) * scenario["progress"] / 100)
            for i in range(tiles_to_complete):
                card.tiles[i].completed = True
                card.tiles[i].completed_at = datetime.now()

            card.started = True
            card.started_at = datetime.now()
            await memory_store.save_bingo_card(card)

            # Check reminder
            print("\n💬 Generating personalized reminder message with LLM...")
            result = await agent.check_reminder_for_user(scenario["user_id"])

            if result.reminder_decision and result.reminder_decision.message_text:
                decision = result.reminder_decision
                print(f"\n✅ Reminder Generated!")
                print(f"   Template: {decision.message_template.value if decision.message_template else 'N/A'}")
                print(f"   Action: {decision.action.value}")
                print(f"\n   📱 Message:")
                print(f"   \"{decision.message_text}\"")

                print(f"\n💡 Notice how the LLM:")
                print(f"   - Personalizes tone based on user's state")
                print(f"   - Uses encouraging language without pressure")
                print(f"   - Adapts urgency to the situation")
            else:
                print(f"\n⏸️ No reminder needed: {result.reminder_decision.reason}")

        else:
            print(f"⚠️ No active card found for {scenario['name']}")

        await asyncio.sleep(1)


async def demo_comparison():
    """Demo 3: Compare Standard vs LLM-Enhanced Output"""
    print_section("DEMO 3: Comparison - Standard vs LLM-Enhanced")

    memory_store = SQLiteMemoryStore(db_path="./llm_demo.db")
    await memory_store.initialize()

    # Import standard agent
    from src.graph import BingoAgentGraph

    # Create test user
    user_id = "comparison_user"
    user_profile = UserProfile(
        user_id=user_id,
        current_engagement_state=EngagementState.STATE_4_ACTIVE,
        behavioral_archetype=BehavioralArchetype.DRIVER_HEAVY,
        trip_history=TripHistory(
            primary_modes=[TransportMode.DRIVING],
            trip_frequency=15,
        ),
        bingo_history=BingoHistory(
            cards_offered=3,
            cards_participated=2,
            cards_completed=1,
        )
    )
    await memory_store.save_user_profile(user_profile)

    print("Generating cards with both approaches...\n")

    # Standard card
    print("📦 Standard Card Generator (Rule-Based):")
    print("─" * 70)
    standard_agent = BingoAgentGraph(memory_store)
    standard_result = await standard_agent.generate_card_for_user(user_id)

    if standard_result.card_generation_response.success:
        card = standard_result.card_generation_response.card
        print("Sample tiles:")
        for i, tile in enumerate(card.tiles[:5], 1):
            print(f"   {i}. {tile.description}")
        print("   ...")

        # Delete this card so we can generate another
        # In real scenario, you'd use different users
        import os
        if os.path.exists("./bingo_agent.db"):
            await memory_store.get_active_card(user_id)  # Just to keep the connection

    print("\n")

    # LLM card
    print("🤖 LLM-Enhanced Card Generator (GPT-4o-mini):")
    print("─" * 70)

    # Update user to allow new card
    await asyncio.sleep(1)

    llm_agent = LLMBingoAgentGraph(memory_store)
    # Create a new user for LLM
    llm_user_id = "comparison_user_llm"
    user_profile.user_id = llm_user_id
    await memory_store.save_user_profile(user_profile)

    llm_result = await llm_agent.generate_card_for_user(llm_user_id)

    if llm_result.card_generation_response.success:
        card = llm_result.card_generation_response.card
        print("Sample tiles:")
        for i, tile in enumerate(card.tiles[:5], 1):
            print(f"   {i}. {tile.description}")
        print("   ...")

    print("\n" + "─" * 70)
    print("\n💡 Key Differences:")
    print("   Standard: Predictable, template-based, functional")
    print("   LLM-Enhanced: Personalized, engaging, context-aware")
    print("   Both have their place - LLM for engagement, standard for reliability")


async def demo_error_handling():
    """Demo 4: Demonstrate Fallback Behavior"""
    print_section("DEMO 4: Error Handling and Fallback")

    print("The LLM agent has built-in fallback mechanisms:\n")

    print("✅ Fallback Scenarios:")
    print("   1. If LLM API is unavailable → Falls back to rule-based generation")
    print("   2. If LLM returns invalid JSON → Uses standard tile templates")
    print("   3. If LLM message is too long → Truncates or uses template")
    print("   4. If rate limit exceeded → Graceful degradation to standard mode")

    print("\n🛡️ This ensures:")
    print("   • System remains operational even if OpenAI API is down")
    print("   • Users always receive cards and reminders")
    print("   • Performance is maintained under load")
    print("   • No dependency on external services for core functionality")

    print("\n💡 Best Practice:")
    print("   Use LLM features for enhanced UX, but design for graceful degradation")


async def main():
    """Run all demos"""
    print("\n" + "="*70)
    print("  🎮 BINGO CARD AGENT - LLM ENHANCEMENT DEMO")
    print("  Powered by GPT-4o-mini")
    print("="*70)

    # Check API key
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("\n❌ ERROR: OPENAI_API_KEY not found in environment!")
        print("   Please set your API key in .env file")
        return

    print(f"\n✅ API Key configured: {api_key[:20]}...")

    try:
        await demo_llm_card_generation()
        await demo_llm_reminder_messages()
        await demo_comparison()
        await demo_error_handling()

        print_section("DEMO COMPLETE!")
        print("🎉 All demos completed successfully!")
        print("\n📚 Next Steps:")
        print("   1. Review the generated cards and messages")
        print("   2. Try different user profiles and scenarios")
        print("   3. Experiment with temperature and max_tokens in .env")
        print("   4. Integrate into your application using the API")
        print("\n💡 Tip: Check llm_demo.db to see all generated data")

    except Exception as e:
        logger.error(f"Error running demos: {e}", exc_info=True)
        print(f"\n❌ Demo failed: {e}")
        print("   Check logs for details")


if __name__ == "__main__":
    asyncio.run(main())
